---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MAN_IP:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:

inputs:
- name: delete-opsman

run:
  path: ./delete-opsman/task.sh
