---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  STORAGE_NAMES:
  NETWORK_NAME:
  VCENTER_NETWORK:
  DEPLOYMENT_NW_CIDR:
  EXCLUDED_RANGE:
  DEPLOYMENT_NW_DNS:
  DEPLOYMENT_NW_GATEWAY:
  AZ_1:
  AZ_1_CUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_2:
  AZ_2_CUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_3:
  AZ_3_CUSTER_NAME:
  AZ_3_RP_NAME:
  NTP_SERVER_IPS:
  OPS_DIR_HOSTNAME:

inputs:
  - name: concourse-vsphere

run:
  path: concourse-vsphere/tasks/config-opsdir/task.sh
