pivnet_token: # [R] PivNet Access Token
github_token: # [R] Your github token
github_repo: https://github.com/rahul-kj/concourse-vsphere # [R] Pipelines github repo
github_branch: master
github_username: # [R] Your github username

company_proxy_domain: # [O] proxy domain
iaas_type: vsphere

## Ops Manager installation meta data
om_ip: # [O] Ops Manager IP if behind proxy
om_fqdn: # [R] Ops Manager FQDN, ex: opsmgr.example.com
om_usr: # [R] Ops Manager admin user
om_pwd: # [R] Ops Manager admin password

product_name: isolation-segment
product_identifier: p-isolation-segment

om_generate_ssl_endpoint: /api/v0/certificates/generate
singleton_jobs_az: # [R] Place singleton jobs in an AZ
other_azs: # [R] Balance other jobs in AZ's
deployment_nw: # [R] Tile network name
isolation_segment_domain: # [R] Isolation segment domain. ex: cfis.example.com
ssl_termination_point: terminate_at_router # [R] terminate_at_router|terminate_at_router_ert_cert|terminate_before_router
ssl_rsa_certificate: # [O] TLS Termination Public Certificates
ssl_private_key: # [O] TLS Termination Private Certificates
router_ssl_cipher: # [O] Router ciphers are read in Golang and should use underscores instead of dashes in their names e.g. TLS_RSA_WITH_RC4_128_SHA:TLS_RSA_WITH_AES_128_CBC_SHA
router_static_ips: # [O] Enter static IP address(es) for the Router(s), which must be within the subnet CIDR block that you defined in the Ops Manager network configuration. If you have a load balancer, configure it to point to these IPs.
cell_disk_capacity: # [O] Cell Disk Capacity (MB)
cell_memory_capacity: # [O] Cell Memory Capacity (MB)
dns_servers: # [O] List of DNS Servers
application_network_cidr: 10.254.0.0/22 # [R] Applications Subnet (Only change this if you need to avoid address collision with a third-party service on the same subnet.)
application_network_mtu: 1454 # [R] Applications Network Maximum Transmission Unit (MTU) (in bytes)
insecure_docker_registry_list: # [O] Private Docker Insecure Registry Whitelist
isolation_segment_name: # [R] Segment Name
router_instances: # [R] Router instances, integer

diego_cell_instances: # [R] Diego Cell instances, integer
isolated_router_instance_type: micro # [R] micro|nano|small|medium|large - refer to the deployment cloud config for more options
diego_cell_instance_type: xlarge.disk # [R] small.disk|large.disk|xlarge.disk - refer to the deployment cloud config for more options
