resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: {{github_token}}

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

- name: concourse-vsphere
  type: git
  source:
    uri: git@github.com:rahul-kj/concourse-vsphere
    branch: master
    private_key: {{github_private_key}}

- name: pivnet-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    #product_version: 1.10-alpha1
    #sort_by: semver

jobs:

- name: delete-opsmgr
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: govc
    - get: om-cli
      globs: om-linux
    - get: pivnet-product
      params:
        globs:
        - "*.ova"
      trigger: true

  - task: delete-products
    file: concourse-vsphere/tasks/delete-products/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

  - task: delete-opsman
    file: concourse-vsphere/tasks/delete-opsman/task.yml
    params:
      OPS_MGR_IP: {{om_ip}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_USR: {{vcenter_usr}}
      VCENTER_PWD: {{vcenter_pwd}}

- name: install-opsmgr
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: govc
    - get: om-cli
      globs: om-linux
    - get: pivnet-product
      params:
        globs:
        - "*.ova"
      trigger: true
      passed: [delete-opsmgr]

  - task: deploy-opsman
    file: concourse-vsphere/tasks/import-opsman/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_DATACENTER: {{vcenter_data_center}}
      GOVC_DATASTORE: {{om_data_store}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OPS_MGR_SSH_PWD: {{ops_mgr_ssh_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
      OM_NTP_SERVERS: {{om_ntp_servers}}
      OM_DNS_SERVERS: {{om_dns_servers}}
      OM_GATEWAY: {{om_gateway}}
      OM_NETMASK: {{om_netmask}}
      OM_IP: {{om_ip}}
      OM_VM_NETWORK: {{om_vm_network}}
      OM_VM_NAME: {{om_vm_name}}
      OM_RESOURCE_POOL: {{om_resource_pool}}
      OM_DISK_TYPE: {{disk_type}}
      OM_VM_POWER_STATE: {{om_vm_power_state}}

  - task: config-opsman
    file: concourse-vsphere/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}

- name: configure-ops-director
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: om-cli
      globs: om-linux
      trigger: true
      passed: [install-opsmgr]

  - task: config-opsdir
    file: concourse-vsphere/tasks/config-opsdir/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_USR: {{vcenter_usr}}
      VCENTER_PWD: {{vcenter_pwd}}
      VCENTER_DATA_CENTER: {{vcenter_data_center}}
      VCENTER_DISK_TYPE: {{disk_type}}
      STORAGE_NAMES: {{storage_names}}
      NETWORK_NAME: {{network_name}}
      VCENTER_NETWORK: {{vm_network}}
      DEPLOYMENT_NW_CIDR: {{deployment_nw_cidr}}
      EXCLUDED_RANGE: {{excluded_range}}
      DEPLOYMENT_NW_DNS: {{deployment_nw_dns}}
      DEPLOYMENT_NW_GATEWAY: {{deployment_nw_gateway}}
      AZ_1: {{az_1_name}}
      AZ_1_CUSTER_NAME: {{az_1_cluster_name}}
      AZ_1_RP_NAME: {{az_1_rp_name}}
      AZ_2: {{az_2_name}}
      AZ_2_CUSTER_NAME: {{az_2_cluster_name}}
      AZ_2_RP_NAME: {{az_2_rp_name}}
      AZ_3: {{az_3_name}}
      AZ_3_CUSTER_NAME: {{az_3_cluster_name}}
      AZ_3_RP_NAME: {{az_3_rp_name}}
      NTP_SERVER_IPS: {{ntp_servers}}
