resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: {{github_token}}

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

- name: concourse-vsphere
  type: git
  source:
    uri: git@github.com:rahul-kj/concourse-vsphere
    branch: master
    private_key: {{git_private_key}}

- name: pivnet-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    sort_by: semver

jobs:
- name: install-opsmgr
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: govc
    - get: om-cli
      globs: om-linux
    - get: pivnet-product
      params:
        globs:
        - "*.ova"

  - task: deploy-opsman
    file: concourse-vsphere/tasks/import-opsman/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_DATACENTER: {{vcenter_data_center}}
      GOVC_DATASTORE: {{om_data_store}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OPS_MGR_SSH_PWD: {{ops_mgr_ssh_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
      OM_NTP_SERVERS: {{om_ntp_servers}}
      OM_DNS_SERVERS: {{om_dns_servers}}
      OM_GATEWAY: {{om_gateway}}
      OM_NETMASK: {{om_netmask}}
      OM_IP: {{om_ip}}
      OM_VM_NETWORK: {{om_vm_network}}
      OM_VM_NAME: {{om_vm_name}}
      OM_RESOURCE_POOL: {{om_resource_pool}}
      OM_DISK_TYPE: {{om_disk_type}}
      OM_VM_POWER_STATE: {{om_vm_power_state}}

  - task: config-opsman
    file: concourse-vsphere/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
