---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MAN_HOST:
  OPS_MAN_USER:
  OPS_MAN_PWD:

inputs:
  - name: concourse-vsphere

run:
  path: concourse-vsphere/delete-products/task.sh
