---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MAN_URL:
  OPS_MAN_USER:
  OPS_MAN_PWD: 

inputs:
- name: delete-products

run:
  path: ./delete-products/task.sh
