# Token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: ((pivnet_token))

# The token used to download the repos from GitHub for the pipelines
github_token: ((github_token)) # [R] Your github token
github_repo: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
github_branch: master
github_username: ((github_username)) # [R] Your github username

iaas_type: vsphere

debug: false

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr))  # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd))  # [R] Ops Manager admin password

product_name: pivotal-rabbitmq-service
product_identifier: p-rabbitmq
product_version: ^1\.11\..*$

singleton_jobs_az: # [R] Place singleton jobs in an AZ
other_azs: # [R] Balance other jobs in AZ's
network_name: # [R] Tile network name
service_network_name: # [R] Services network name

on_demand_broker_global_service_instance_quota: 20
disk_alarm_threshold: mem_relative_1_5 # fixed_50_mb|mem_relative_1_0|mem_relative_1_5|mem_relative_2_0
metrics_polling_interval: 30
on_demand_broker_dedicated_cluster_plan_selector: disabled # enabled|disabled
on_demand_broker_dedicated_cluster_plan_selector_enabled_cf_service_access: enable # disable|enable
on_demand_broker_dedicated_cluster_plan_selector_enabled_description: ''
on_demand_broker_dedicated_cluster_plan_selector_enabled_disk_limit_acknowledgement: "non-existant-value" # non-existant-value|acknowledge
on_demand_broker_dedicated_cluster_plan_selector_enabled_features: RabbitMQ
on_demand_broker_dedicated_cluster_plan_selector_enabled_instance_quota: 0
on_demand_broker_dedicated_cluster_plan_selector_enabled_name: cluster
on_demand_broker_dedicated_cluster_plan_selector_enabled_rabbitmq_az_placement:
on_demand_broker_dedicated_cluster_plan_selector_enabled_rabbitmq_cluster_partition_handling_strategy: pause_minority # pause_minority|autoheal
on_demand_broker_dedicated_cluster_plan_selector_enabled_rabbitmq_number_of_nodes: 3
on_demand_broker_dedicated_cluster_plan_selector_enabled_rabbitmq_persistent_disk_type: 1024
on_demand_broker_dedicated_cluster_plan_selector_enabled_rabbitmq_vm_type: nano
on_demand_broker_dedicated_single_node_plan_cf_service_access: disable
on_demand_broker_dedicated_single_node_plan_description: ''
on_demand_broker_dedicated_single_node_plan_disk_limit_acknowledgement: "non-existant-value" # non-existant-value|acknowledge
on_demand_broker_dedicated_single_node_plan_features: RabbitMQ
on_demand_broker_dedicated_single_node_plan_instance_quota: 0
on_demand_broker_dedicated_single_node_plan_name: solo
on_demand_broker_dedicated_single_node_plan_rabbitmq_az_placement:
on_demand_broker_dedicated_single_node_plan_rabbitmq_persistent_disk_type: 1024
on_demand_broker_dedicated_single_node_plan_rabbitmq_vm_type: nano
on_demand_broker_vm_extensions: 'public_ip' # 'public_ip'|''
syslog_selector: disabled # enabled|disabled
syslog_selector_enabled_address: ''
syslog_selector_enabled_port: ''
syslog_selector_enabled_syslog_ca_cert: ''
syslog_selector_enabled_syslog_format: ''
syslog_selector_enabled_syslog_permitted_peer: ''
syslog_selector_enabled_syslog_tls: ''
syslog_selector_enabled_syslog_transport: ''
rabbitmq_broker_dns_host: ''
rabbitmq_broker_operator_set_policy_enabled: ''
rabbitmq_broker_policy_definition: ''
rabbitmq_haproxy_static_ips: ''
rabbitmq_server_cluster_partition_handling: pause_minority # pause_minority|autoheal
rabbitmq_server_config: ''
rabbitmq_server_cookie: ''
rabbitmq_server_plugins: 'rabbitmq_amqp1_0,rabbitmq_auth_backend_ldap,rabbitmq_auth_mechanism_ssl,rabbitmq_consistent_hash_exchange,rabbitmq_federation,rabbitmq_federation_management,rabbitmq_management,rabbitmq_management_visualiser,rabbitmq_mqtt,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_stomp,rabbitmq_tracing,rabbitmq_web_stomp,rabbitmq_web_stomp_examples,rabbitmq_event_exchange,rabbitmq_jms_topic_exchange'
rabbitmq_server_ports: '15672,5672,5671,1883,8883,61613,61614,15674'
rabbitmq_server_ssl_cert_pem: ''
rabbitmq_server_ssl_private_key_pem: ''
rabbitmq_server_server_admin_username: ''
rabbitmq_server_server_admin_password: ''
rabbitmq_server_ssl_cacert: ''
rabbitmq_server_ssl_fail_if_no_peer_cert: false
rabbitmq_server_ssl_verification_depth: 5
rabbitmq_server_ssl_verify: false
rabbitmq_server_ssl_versions: "tlsv1.1,tlsv1.2"
rabbitmq_server_static_ips: ''
rabbitmq_server_instances: 3
rabbitmq_server_instance_type: large
rabbitmq_server_persistent_disk_mb: 30720
rabbitmq_haproxy_instances: 1
rabbitmq_haproxy_instance_type: small
rabbitmq_broker_instances: 1
rabbitmq_broker_instance_type: small
on_demand_broker_instances: 1
on_demand_broker_instance_type: micro
on_demand_broker_persistent_disk_mb: 1024

errands_to_disable: # (broker-registrar|multitenant-smoke-tests|register-on-demand-service-broker|dedicated-instance-smoke-tests|upgrade-all-service-instances)

concourse_user: ((concourse_user))
concourse_pwd: ((concourse_pwd))
concourse_url: ((concourse_url))
pipeline-name: install-rabbitmq
team-name: ((team-name))
upgrade-pipeline-name: upgrade-rabbitmq
