pivnet_token: # [R] PivNet Access Token
github_token: # [R] Your github token

company_proxy_domain: # [O] proxy domain
iaas_type: vsphere

## Ops Manager installation meta data
ops_mgr_ip: # [O] Ops Manager IP if behind proxy
ops_mgr_host: # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: # [R] Ops Manager admin user
ops_mgr_pwd: # [R] Ops Manager admin password

product_name: pivotal-rabbitmq-service
product_identifier: p-rabbitmq
product_version: ^1\.10\..*$

ops_mgr_generate_ssl_endpoint: /api/v0/certificates/generate

singleton_jobs_az: # [R] Place singleton jobs in an AZ
other_azs: # [R] Balance other jobs in AZ's
network_name: # [R] Tile network name
services_network_name: # [R] Services network name

metrics_polling_interval: 30 # min: 10
syslog_selector: disabled # (enabled|disabled)
syslog_selector_address:
syslog_selector_port:
syslog_selector_syslog_transport: tcp # (tcp|udp|relp)
syslog_selector_syslog_format: rfc5424 # (rfc5424|job_index_id)
syslog_selector_syslog_tls: false # (true|false)
syslog_selector_syslog_permitted_peer:
syslog_selector_syslog_ca_cert:
on_demand_broker_vm_extensions:
on_demand_broker_dedicated_single_node_plan_cf_service_access: "disable" #(enable|disable)
on_demand_broker_dedicated_single_node_plan_name: "solo"
on_demand_broker_dedicated_single_node_plan_description: "Single node RabbitMQ dedicated instance"
on_demand_broker_dedicated_single_node_plan_instance_quota: 0
on_demand_broker_dedicated_single_node_plan_features: "RabbitMQ"
on_demand_broker_dedicated_single_node_plan_rabbitmq_az_placement:
on_demand_broker_dedicated_single_node_plan_rabbitmq_vm_type:
on_demand_broker_dedicated_single_node_plan_rabbitmq_persistent_disk_type:
on_demand_broker_dedicated_single_node_plan_disk_limit_acknowledgement: "non-existant-value" #(acknowledge|non-existant-value)
on_demand_broker_dedicated_cluster_plan_selector: "disabled" #(enabled|disabled)
on_demand_broker_dedicated_cluster_plan_selector_cf_service_access: "enable" #(enable|disable)
on_demand_broker_dedicated_cluster_plan_selector_name: "cluster"
on_demand_broker_dedicated_cluster_plan_selector_description: "RabbitMQ dedicated cluster"
on_demand_broker_dedicated_cluster_plan_selector_features: "RabbitMQ"
on_demand_broker_dedicated_cluster_plan_selector_instance_quota: 0
on_demand_broker_dedicated_cluster_plan_selector_rabbitmq_persistent_disk_type:
on_demand_broker_dedicated_cluster_plan_selector_rabbitmq_number_of_nodes: 3
on_demand_broker_dedicated_cluster_plan_selector_rabbitmq_cluster_partition_handling_strategy: "pause_minority" #(pause_minority|autoheal)
on_demand_broker_dedicated_cluster_plan_selector_rabbitmq_az_placement:
on_demand_broker_dedicated_cluster_plan_selector_rabbitmq_vm_type:
on_demand_broker_dedicated_cluster_plan_selector_disk_limit_acknowledgement: "non-existant-value" #(acknowledge|non-existant-value)
disk_alarm_threshold: # (fixed_50_mb|mem_relative_1_0|mem_relative_1_5|mem_relative_2_0)
server_admin_username:
server_admin_password:
rabbitmq_server_plugins: "rabbitmq_amqp1_0,rabbitmq_auth_backend_ldap,rabbitmq_auth_mechanism_ssl,rabbitmq_consistent_hash_exchange,rabbitmq_federation,rabbitmq_federation_management,rabbitmq_management,rabbitmq_management_visualiser,rabbitmq_mqtt,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_stomp,rabbitmq_tracing,rabbitmq_web_stomp,rabbitmq_web_stomp_examples,rabbitmq_event_exchange,rabbitmq_jms_topic_exchange"
ssl_cert_pem:
ssl_private_key_pem:
ssl_cacert:
ssl_verify: false # (true|false)
ssl_verification_depth: 5
ssl_fail_if_no_peer_cert: false # (true|false)
rabbitmq_server_cookie:
rabbitmq_server_config:
ssl_versions: tlsv1.1,tlsv1.2 # (tlsv1.0,tlsv1.1,tlsv1.2)
cluster_partition_handling: pause_minority #(pause_minority|autoheal)
rabbitmq_server_ports: "15672, 5672, 5671, 1883, 8883, 61613, 61614, 15674"
rabbitmq_server_static_ips:
rabbitmq_haproxy_static_ips:
rabbitmq_broker_dns_host:
operator_set_policy_enabled: false # (true|false)
policy_definition:
global_service_instance_quota: 20

rmq_server_instance_type: large
rmq_server_instances: 3
rmq_server_node_persistent_disk_size: 30720
rmq_haproxy_instance_type: small
rmq_haproxy_instances: 1
rmq_broker_instance_type: small
rmq_broker_instances: 1 # (0|1)
rmq_ondemand_instance_type: micro
rmq_ondemand_instances: 1 # (0|1)
rmq_ondemand_persistent_disk_size: 1024

errands_to_disable: # (broker-registrar|multitenant-smoke-tests|register-on-demand-service-broker|dedicated-instance-smoke-tests|upgrade-all-service-instances)

concourse_user:
concourse_pwd:
concourse_url:
pipeline-name:
team-name:
upgrade-pipeline-name:
