---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  MYSQL_LOGQUEUE_INSTANCE_COUNT:
  ELASTICSEARCH_LOGQUEUE_INSTANCE_COUNT:
  INGESTOR_INSTANCE_COUNT:
  SERVER_INSTANCE_COUNT:
  LOGS_RETENTION_WINDOW:
  METRICS_RETENTION_WINDOW:
  ELASTICSEARCH_MASTER_INSTANCE_TYPE:
  ELASTICSEARCH_MASTER_INSTANCES:
  ELASTICSEARCH_MASTER_PERSISTENT_DISK_SIZE:
  ELASTICSEARCH_DATA_INSTANCE_TYPE:
  ELASTICSEARCH_DATA_INSTANCES:
  ELASTICSEARCH_DATA_PERSISTENT_DISK_SIZE:
  REDIS_INSTANCE_TYPE:
  REDIS_INSTANCES:
  REDIS_DISK_SIZE:
  MYSQL_INSTANCE_TYPE:
  MYSQL_PERSISTENT_DISK_SIZE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-pcf-metrics/task.sh
