# Token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: <YOUR-PIVNET-TOKEN>

# The token used to download the repos from GitHub for the pipelines
github_token: <YOUR-GITHUB-TOKEN>
github_repo: https://github.com/rahul-kj/concourse-vsphere # [R] Pipelines github repo
github_branch: master
github_username: # [R] Your github username

opsman_product_version: ^2\.0\..*$
ert_product_version: ^2\.0\..*$
iaas_type: vsphere

ci_username: # [R] Username used to push to your gist_url
ci_email_address: # [R] Email used to push to your gist_url

vcenter_host: <VCENTER-HOST-OR-IP>
vcenter_usr: <VCENTER-SERVICE-USR> # If user is tied to a domain, then escape the \, example `domain\\user`
vcenter_pwd: <VCENTER-SERVICE-USR-PWD>
vcenter_data_center: <VCENTER-DATA-CENTER-TO-DEPLOY>
ops_mgr_data_store: <DATA-STORE-TO-DEPLOY-OPS-MANAGER> # vCenter datastore name to deploy Ops Manager on
ops_mgr_vm_host: <DESIRED-VCENTER-HOST-TO-DEPLOY-OM> # Optional - vCenter host to deploy Ops Manager on
ops_mgr_ip: <DESIRED-OPS-MANAGER-IP> # Ops Manager Static IP
ops_mgr_host: <DESIRED-OPS-MANAGER-FQDN> # FQDN to access Ops Manager, ex: opsmgr.example.com
ops_mgr_usr: <DESIRED-OPS-MANAGER-USR> # Ops Manager admin username
ops_mgr_pwd: <DESIRED-OPS-MANAGER-PWD> # Ops Manager admin password
ops_mgr_ssh_pwd: <DESIRED-OPS-MANAGER-SSH-PWD> # Ops Manager ssh password to user ubuntu
ops_mgr_decryption_pwd: <DESIRED-OPS-MANAGER-DECRYPTION-PWD> # Ops Manager decryption password
ops_mgr_ntp_servers: <OPS-MANAGER-NTP-SERVERS> # Comma seperated list of NTP Servers
ops_mgr_dns_servers: <OPS-MANAGER-DNS-SERVERS> # Comma seperated list of DNS Servers
ops_mgr_gateway: <OPS-MANAGER-NETWORK-GATEWAY> # Ops Manager network gateway
ops_mgr_netmask: <OPS-MANAGER-NETWORK-MASK> # Ops Manager network netmask
ops_mgr_vm_network: <OPS-MANAGER-NETWORK-NAME> # vCenter network name to use to deploy Ops Manager on
ops_mgr_vm_name: <OPS-MANAGER-VM-NAME> # Ops Manager VM Name

# vCenter Cluster or Resource Pool to use to deploy Ops Manager.
# The format is
# - `/<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>`
# - or `/<Data Center Name>/host/<Cluster Name>`
ops_mgr_resource_pool: <OPS-MANAGER-RESOURCE-POOL-PATH>
ops_mgr_disk_type: "thick" # Ops Manager VM Disk type, enter thick or thin
ops_mgr_vm_power_state: true # Power on Ops Manager VM after creation. Possible values true/false

vcenter_disk_type: "thick" # BOSH provisioned VM Disk type, enter thick or thin
ephemeral_storage_names: <PCF-EPHEMERAL-STORAGE-NAMES> # Ephemeral Storage names from vCenter for use by PCF
persistent_storage_names: <PCF-PERSISTENT-STORAGE-NAMES> # Persistent Storage names from vCenter for use by PCF
bosh_vm_folder:
bosh_templates_folder:
bosh_disk_path:
nsx_networking_enabled: # true or false
nsx_mode: # [O] nsx-v or nsx-t
nsx_address:
nsx_password:
nsx_username:
nsx_ca_certificate:
ssl_verification_enabled: # true or false
ntp_servers:
enable_vm_resurrector: # true or false
metrics_ip:
opentsdb_ip:
post_deploy_enabled: # true or false
bosh_recreate_on_next_deploy: # true or false
retry_bosh_deploys: # true or false
keep_unreachable_vms: # true or false
max_threads: 8
director_worker_count:
ops_dir_hostname:
pager_duty_enabled:
pager_duty_service_key:
pager_duty_http_proxy:
hm_email_enabled: # true or false
smtp_host:
smtp_port:
smtp_domain:
from_address:
recipients_address:
smtp_user:
smtp_password:
smtp_tls_enabled:
blobstore_type: # local or s3
s3_endpoint:
s3_bucket_name:
s3_access_key:
s3_secret_key:
s3_signature_version:
database_type: # internal or external
external_mysql_db_host:
external_mysql_db_port:
external_mysql_db_user:
external_mysql_db_password:
external_mysql_db_database:
syslog_enabled: # true or false
syslog_address:
syslog_port:
syslog_transport_protocol:
syslog_tls_enabled: # true or false
syslog_permitted_peer:
syslog_ssl_ca_certificate:

## Network configuration for Ops Director
icmp_checks_enabled: true # Configure if ICMP checks are allowed, possible values true or false
infra_network_name: "INFRASTRUCTURE"
infra_vsphere_network: # vCenter Infrastructure network name
infra_nw_cidr: # Infrastructure network CIDR, ex: 10.0.0.0/22
infra_excluded_range: # Infrastructure network exclusion range
infra_nw_dns: # Infrastructure network DNS
infra_nw_gateway: # Infrastructure network Gateway
infra_nw_azs: # Comma seperated list of AZ's to be associated with this network

deployment_network_name: "DEPLOYMENT"
deployment_vsphere_network: # vCenter Deployment network name
deployment_nw_cidr: # Deployment network CIDR, ex: 10.0.0.0/22
deployment_excluded_range: # Deployment network exclusion range
deployment_nw_dns: # Deployment network DNS
deployment_nw_gateway: # Deployment network Gateway
deployment_nw_azs: # Comma seperated list of AZ's to be associated with this network

services_network_name: "SERVICES"
services_vsphere_network: # vCenter Services network name
services_nw_cidr: # Services network CIDR, ex: 10.0.0.0/22
services_excluded_range: # Services network exclusion range
services_nw_dns: # Services network DNS
services_nw_gateway: # Services network Gateway
services_nw_azs: # Comma seperated list of AZ's to be associated with this network
services_nw_is_service_nw: false # true/false - set if this is a services network

dynamic_services_network_name: "DYNAMIC-SERVICES"
dynamic_services_vsphere_network: # vCenter Dynamic Services network name
dynamic_services_nw_cidr: # Dynamic Services network CIDR, ex: 10.0.0.0/22
dynamic_services_excluded_range: # Dynamic Services network exclusion range
dynamic_services_nw_dns: # Dynamic Services network DNS
dynamic_services_nw_gateway: # Dynamic Services network Gateway
dynamic_services_nw_azs: # Comma seperated list of AZ's to be associated with this network
dynamic_services_nw_is_service_nw: true # true/false - set if this is a services network

## AZ configuration for Ops Director
az_1_name: <az1-name> # AZ1 logical name. No spaces or special characters
az_1_cluster_name: <vcenter-az1-cluster-name> # vCenter Cluster name for AZ1
az_1_rp_name: <vcenter-az1-resource-pool-name> # vCenter Resource Pool name for AZ1

az_2_name: <az2-name> # AZ2 logical name. No spaces or special characters
az_2_cluster_name: <vcenter-az2-cluster-name> # vCenter Cluster name for AZ2
az_2_rp_name: <vcenter-az2-resource-pool-name> # vCenter Resource Pool name for AZ2

az_3_name: <az3-name> # AZ3 logical name. No spaces or special characters
az_3_cluster_name: <vcenter-az3-cluster-name> # vCenter Cluster name for AZ3
az_3_rp_name: <vcenter-az3-resource-pool-name> # vCenter Resource Pool name for AZ3

trusted_certificates:
generate_vm_passwords:
director_instance_type: 1
director_instances: large.disk
director_persistent_disk_size_mb: 51200
compilation_instance_type: large.cpu
compilation_instances: 4

ert_singleton_job_az: # AZ to use for deployment of ERT Singleton jobs
deployment_nw_azs:
network_name:
ops_mgr_generate_ssl_endpoint:
cc_api_rate_limit:
general_limit:
unauthenticated_limit:
credhub_key_encryption_name:
credhub_key_encryption_secret: # Should be 12 characters or more
credhub_key_encryption_is_primary: true # (true|false)
secure_service_instance_credentials: false # (true|false)
credhub_database: # external or internal_mysql
credhub_database_external_host:
credhub_database_external_port:
credhub_database_external_username:
credhub_database_external_password:
credhub_database_external_tls_ca:
nfs_volume_driver: # enable or disable
ldap_service_account_user:
ldap_service_account_password:
ldap_server_host:
ldap_server_port:
ldap_user_fqdn:
garden_disk_cleanup:
enable_grootfs: # true or false
logger_endpoint_port:
syslog_host:
syslog_port:
syslog_protocol:
syslog_tls: # enabled or disabled
tls_ca_cert:
tls_permitted_peer:
networking_poe_ssl_name:
networking_poe_ssl_cert_pem:
networking_poe_ssl_cert_private_key_pem:
routing_custom_ca_certificates:
routing_disable_http: # true or false
routing_minimum_tls_version: # tls_v1_0 or tls_v1_1 or tls_v1_2
routing_tls_termination: load_balancer # (load_balancer|ha_proxy|router)
gorouter_ssl_ciphers: # ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
haproxy_ssl_ciphers: # DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
haproxy_max_buffer_size:
haproxy_forward_tls:
haproxy_forward_tls_backend_ca:
tcp_routing: # enable or disable
tcp_reservable_ports:
router_backend_max_conn: 500
route_services:
ignore_ssl_cert_verification: # true or false
container_networking: # enable or disable
container_networking_interface_plugin: silk # (silk|external)
container_networking_network_mtu: 1454
container_networking_network_cidr: ""
container_networking_vtep_port: 4789
iptables_denied_logs_per_sec: 1
iptables_accepted_udp_logs_per_sec: 100
enable_log_traffic: false
cf_networking_enable_space_developer_self_service: false
security_acknowledgement: X
cf_dial_timeout_in_seconds:
smoke_tests:
smoke_tests_org_name:
smoke_tests_space_name:
smoke_tests_apps_domain:
smtp_from:
smtp_address:
smtp_port:
smtp_identity:
smtp_password:
smtp_enable_starttls_auto:
smtp_auth_mechanism:
smtp_crammd5_secret:
system_blobstore: # internal or s3 or azure or gcs
s3_endpoint:
s3_buildpacks_bucket:
s3_droplets_bucket:
s3_packages_bucket:
s3_resources_bucket:
s3_access_key:
s3_secret_key:
s3_signature_version:
s3_region:
s3_encryption:
gcs_buildpacks_bucket:
gcs_buildpacks_bucket:
gcs_packages_bucket:
gcs_resources_bucket:
gcs_access_key:
gcs_secret_key:
azure_buildpacks_container:
azure_droplets_container:
azure_packages_container:
azure_resources_container:
azure_account_name:
azure_access_key:
system_database: # internal_mysql or external
external_mysql_host:
external_mysql_port:
external_mysql_account_username:
external_mysql_account_password:
external_mysql_app_usage_service_username:
external_mysql_app_usage_service_password:
external_mysql_autoscale_username:
external_mysql_autoscale_password:
external_mysql_ccdb_username:
external_mysql_ccdb_password:
external_mysql_diego_username:
external_mysql_diego_password:
external_mysql_locket_username:
external_mysql_locket_password:
external_mysql_networkpolicyserver_username:
external_mysql_networkpolicyserver_password:
external_mysql_nfsvolume_username:
external_mysql_nfsvolume_password:
external_mysql_notifications_username:
external_mysql_notifications_password:
external_mysql_routing_username:
external_mysql_routing_password:
external_mysql_silk_username:
external_mysql_silk_password:
mysql_backups: # enable or disable
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:
mysql_backups_s3_backup_all_masters:
mysql_backups_s3_region:
mysql_backups_gcs_service_account_json:
mysql_backups_gcs_project_id:
mysql_backups_gcs_bucket_name:
mysql_backups_gcs_cron_schedule:
mysql_backups_gcs_backup_all_masters:
mysql_backups_azure_storage_account:
mysql_backups_azure_storage_access_key:
mysql_backups_azure_container:
mysql_backups_azure_path:
mysql_backups_azure_cron_schedule:
mysql_backups_azure_backup_all_masters:
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:
mysql_backups_scp_backup_all_masters:
mysql_activity_logging: # enable or disable
mysql_activity_logging_audit_logging_events: connect,query
uaa_auth: # internal or ldap or saml
password_min_length:
password_min_uppercase:
password_min_lowercase:
password_min_numeric:
password_min_special:
password_expires_after_months:
password_max_retry:
saml_sso_name:
saml_display_name:
saml_sso_url:
saml_name_id_format:
saml_sso_xml:
saml_sign_auth_requests:
saml_require_signed_assertions:
saml_email_domains:
saml_first_name_attribute:
saml_last_name_attribute:
saml_email_attribute:
saml_external_groups_attribute:
saml_signature_algorithm:
ldap_url:
ldap_identity:
ldap_password:
ldap_search_base:
ldap_search_filter:
ldap_group_search_base:
ldap_group_search_filter:
ldap_server_ssl_cert:
ldap_server_ssl_cert_alias:
ldap_mail_attribute_name:
ldap_email_domains:
ldap_first_name_attribute:
ldap_last_name_attribute:
ldap_ldap_referrals:
uaa_database:
uaa_database_host:
uaa_database_port:
uaa_database_username:
uaa_database_password:
blobstore_internal_access_rules: "allow 10.0.0.0/8;,allow 172.16.0.0/12;,allow 192.168.0.0/16;"
mysql_proxy_static_ips:
mysql_proxy_service_hostname:
mysql_proxy_startup_delay:
mysql_proxy_shutdown_delay:
mysql_cli_history:
mysql_cluster_probe_timeout:
prevent_node_auto_rejoin: false #(true|false)
remote_admin_access: false #(true|false)
uaa_private_key_pem:
uaa_cert_pem:
uaa_private_key_passphrase:
apps_manager_access_token_lifetime:
apps_manager_refresh_token_lifetime:
cf_cli_access_token_lifetime:
cf_cli_refresh_token_lifetime:
customize_username_label:
customize_password_label:
proxy_ips_regex:
issuer_uri:
cloud_controller_encrypt_key:
max_file_size:
default_app_memory:
max_disk_quota_app:
default_disk_quota_app:
enable_custom_buildpacks:
system_domain:
apps_domain:
default_quota_memory_limit_mb:
default_quota_max_number_services:
staging_timeout_in_seconds:
allow_app_ssh_access:
default_app_ssh_access:
security_event_logging_enabled: # true or false
ha_proxy_static_ips:
skip_cert_verify: # true or false
protected_domains:
trusted_domain_cidrs:
router_static_ips:
disable_insecure_cookies: # true or false
request_timeout_in_seconds:
frontend_idle_timeout: 900
drain_wait:
lb_healthy_threshold:
enable_zipkin: # true or false
max_idle_connections:
extra_headers_to_log: # true or false
enable_isolated_routing: # true or false
mysql_monitor_poll_frequency:
mysql_monitor_write_read_delay:
mysql_monitor_recipient_email:
diego_brain_static_ips:
starting_container_count_maximum:
executor_disk_capacity:
executor_memory_capacity:
insecure_docker_registry_list:
message_drain_buffer_size:
tcp_router_static_ips:
company_name:
accent_color:
global_wrapper_bg_color:
global_wrapper_text_color:
global_wrapper_header_content:
global_wrapper_footer_content:
logo:
square_logo:
footer_text:
footer_links:
nav_links_name_1:
nav_links_href_1:
nav_links_name_2:
nav_links_href_2:
nav_links_name_3:
nav_links_href_3:
apps_manager_product_name:
marketplace_name:
enable_invitations:
display_plan_prices:
currency_lookup:
consul_server_instance_type:
consul_server_instances:
consul_server_persistent_disk_size_mb:
nats_instance_type:
nats_instances:
nfs_server_instance_type:
nfs_server_instances:
nfs_server_persistent_disk_size_mb:
mysql_proxy_instance_type:
mysql_proxy_instances:
mysql_instance_type:
mysql_instances:
mysql_instance_persistent_disk_size_mb:
backup_prepare_instance_type:
backup_prepare_instances:
backup_prepare_persistent_disk_size_mb:
uaa_instance_type:
uaa_instances:
cloud_controller_instance_type:
cloud_controller_instances:
ha_proxy_instance_type:
ha_proxy_instances:
router_instance_type:
router_instances:
mysql_monitor_instance_type:
mysql_monitor_instances:
clock_global_instance_type:
clock_global_instances:
cloud_controller_worker_instance_type:
cloud_controller_worker_instances:
diego_database_instance_type:
diego_database_instances:
diego_brain_instance_type:
diego_brain_instances:
diego_brain_persistent_disk_size_mb:
diego_cell_instance_type:
diego_cell_instances:
doppler_instance_type:
doppler_instances:
loggregator_tc_instance_type:
loggregator_tc_instances:
tcp_router_instance_type:
tcp_router_instances:
tcp_router_persistent_disk_size_mb:
syslog_adapter_instance_type:
syslog_adapter_instances:
credhub_instance_type:
credhub_instances:
