---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_NAME:
  HEALTHWATCH_FORWARDER_BOSHHEALTH_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_BOSHTASKS_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_CANARY_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_CLI_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_FOUNDATION_NAME:
  HEALTHWATCH_FORWARDER_HEALTH_CHECK_AZ:
  HEALTHWATCH_FORWARDER_HEALTH_CHECK_VM_TYPE:
  HEALTHWATCH_FORWARDER_INGESTOR_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_OPSMAN_INSTANCE_COUNT:
  MYSQL_SKIP_NAME_RESOLVE:
  OPSMAN:
  OPSMAN_ENABLE_URL:
  MYSQL_PERSISTENT_DISK_MB:
  MYSQL_INSTANCES:
  MYSQL_INSTANCE_TYPE:
  PROXY_INSTANCES:
  PROXY_INSTANCE_TYPE:
  HEALTHWATCH_FORWARDER_PERSISTENT_DISK_MB:
  HEALTHWATCH_FORWARDER_INSTANCES:
  HEALTHWATCH_FORWARDER_INSTANCE_TYPE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-p-healthwatch/task.sh
