---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PRODUCT_NAME:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  OTHER_AZS:
  NETWORK_NAME:
  PLAN_NAME: "100mb"
  PLAN_DESCRIPTION: "100MB default"
  PLAN_MAX_STORAGE_MB: 100
  PLAN_MAX_USER_CONNECTIONS: 40
  PLAN_INVISIBLE: false

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-mysql/task.sh
