---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  REPLICATOR_NAME:

inputs:
  - name: concourse-vsphere
  - name: om-cli
  - name: pivnet-product
  - name: replicator

outputs:
  - name: replicator-tile

run:
  path: concourse-vsphere/tasks/replicate-and-upload-tile/task.sh
