resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: {{github_token}}

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: {{github_token}}

- name: concourse-vsphere
  type: git
  source:
    uri: git@github.com:rahul-kj/concourse-vsphere
    branch: master
    private_key: {{github_private_key}}

- name: pivnet-opsman-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager

- name: pivnet-er-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime

- name: pivnet-metrics-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-metrics

jobs:

- name: delete-opsmgr
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: govc
      params:
        globs:
        - "*linux_amd64*"
    - get: om-cli
      globs: om-linux
    - get: pivnet-opsman-product
      params:
        globs:
        - "*.ova"
      trigger: true

  - task: delete-products
    file: concourse-vsphere/tasks/delete-products/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

  - task: delete-opsman
    file: concourse-vsphere/tasks/delete-opsman/task.yml
    params:
      OPS_MGR_IP: {{om_ip}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_USR: {{vcenter_usr}}
      VCENTER_PWD: {{vcenter_pwd}}

- name: install-opsmgr
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [delete-opsmgr]
      trigger: true
    - get: govc
      params:
        globs:
        - "*linux_amd64*"
      passed: [delete-opsmgr]
    - get: om-cli
      globs: om-linux
      passed: [delete-opsmgr]
    - get: pivnet-opsman-product
      params:
        globs:
        - "*.ova"

  - task: deploy-opsman
    file: concourse-vsphere/tasks/import-opsman/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_DATACENTER: {{vcenter_data_center}}
      GOVC_DATASTORE: {{om_data_store}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OPS_MGR_SSH_PWD: {{ops_mgr_ssh_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
      OM_NTP_SERVERS: {{om_ntp_servers}}
      OM_DNS_SERVERS: {{om_dns_servers}}
      OM_GATEWAY: {{om_gateway}}
      OM_NETMASK: {{om_netmask}}
      OM_IP: {{om_ip}}
      OM_VM_NETWORK: {{om_vm_network}}
      OM_VM_NAME: {{om_vm_name}}
      OM_RESOURCE_POOL: {{om_resource_pool}}
      OM_DISK_TYPE: {{disk_type}}
      OM_VM_POWER_STATE: {{om_vm_power_state}}

  - task: config-opsman
    file: concourse-vsphere/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}

- name: configure-ops-director
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [install-opsmgr]
      trigger: true
    - get: om-cli
      globs: om-linux
      passed: [install-opsmgr]

  - task: config-opsdir
    file: concourse-vsphere/tasks/config-opsdir/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_USR: {{vcenter_usr}}
      VCENTER_PWD: {{vcenter_pwd}}
      VCENTER_DATA_CENTER: {{vcenter_data_center}}
      VCENTER_DISK_TYPE: {{disk_type}}
      STORAGE_NAMES: {{storage_names}}
      NETWORK_NAME: {{network_name}}
      VCENTER_NETWORK: {{vm_network}}
      DEPLOYMENT_NW_CIDR: {{deployment_nw_cidr}}
      EXCLUDED_RANGE: {{excluded_range}}
      DEPLOYMENT_NW_DNS: {{deployment_nw_dns}}
      DEPLOYMENT_NW_GATEWAY: {{deployment_nw_gateway}}
      AZ_1: {{az_1_name}}
      AZ_1_CUSTER_NAME: {{az_1_cluster_name}}
      AZ_1_RP_NAME: {{az_1_rp_name}}
      AZ_2: {{az_2_name}}
      AZ_2_CUSTER_NAME: {{az_2_cluster_name}}
      AZ_2_RP_NAME: {{az_2_rp_name}}
      AZ_3: {{az_3_name}}
      AZ_3_CUSTER_NAME: {{az_3_cluster_name}}
      AZ_3_RP_NAME: {{az_3_rp_name}}
      NTP_SERVER_IPS: {{ntp_servers}}
      OPS_DIR_HOSTNAME: {{ops_dir_hostname}}

- name: opsman-apply-changes
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [configure-ops-director]
    - get: om-cli
      globs: om-linux
      passed: [configure-ops-director]

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

- name: upload-elastic-runtime-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [opsman-apply-changes]
    - get: pivnet-er-product
      params:
        globs:
        - "*.pivotal"
    - get: om-cli
      globs: om-linux
      passed: [opsman-apply-changes]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-er-tile
    file: concourse-vsphere/tasks/upload-er-tile/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      PIVNET_API_TOKEN: {{pivnet_token}}

- name: config-elastic-runtime-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [upload-elastic-runtime-tile]
    - get: om-cli
      globs: om-linux
      passed: [upload-elastic-runtime-tile]

  - task: config-er-tile
    file: concourse-vsphere/tasks/config-ert/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      AZ_2: {{az_2_name}}
      AZ_3: {{az_3_name}}
      NETWORK_NAME: {{network_name}}
      SYSLOG_HOST: {{syslog_host}}
      SYSLOG_PORT: {{syslog_port}}
      SYSLOG_PROTOCOL: {{syslog_protocol}}
      LOGGREGATOR_ENDPOINT_PORT: {{loggregator_endpoint_port}}
      SSL_CERT: {{ssl_cert}}
      SSL_PRIVATE_KEY: {{ssl_private_key}}
      DISABLE_HTTP_PROXY: {{disable_http_proxy}}
      TCP_ROUTING: {{tcp_routing}}
      TCP_ROUTING_PORTS: {{tcp_routing_ports}}
      ROUTE_SERVICES: {{route_services}}
      IGNORE_SSL_CERT: {{ignore_ssl_cert_verification}}
      SMTP_FROM: {{smtp_from}}
      SMTP_ADDRESS: {{smtp_address}}
      SMTP_PORT: {{smtp_port}}
      SMTP_USER: {{smtp_user}}
      SMTP_PWD: {{smtp_pwd}}
      SMTP_AUTH_MECHANISM: {{smtp_auth_mechanism}}
      LDAP_URL: {{ldap_url}}
      LDAP_USER: {{ldap_user}}
      LDAP_PWD: {{ldap_pwd}}
      SEARCH_BASE: {{search_base}}
      SEARCH_FILTER: {{search_filter}}
      GROUP_SEARCH_BASE: {{group_search_base}}
      GROUP_SEARCH_FILTER: {{group_search_filter}}
      MAIL_ATTR_NAME: {{mail_attribute_name}}
      FIRST_NAME_ATTR: {{first_name_attribute}}
      LAST_NAME_ATTR: {{last_name_attribute}}
      SYSTEM_DOMAIN: {{system_domain}}
      APPS_DOMAIN: {{apps_domain}}
      HA_PROXY_IPS: {{ha_proxy_ips}}
      SKIP_CERT_VERIFY: {{skip_cert_verify}}
      ROUTER_STATIC_IPS: {{router_static_ips}}
      MYSQL_MONITOR_EMAIL: {{mysql_monitor_email}}
      TCP_ROUTER_STATIC_IPS: {{tcp_router_static_ips}}
      SSH_STATIC_IPS: {{ssh_static_ips}}

- name: product-apply-changes
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [config-elastic-runtime-tile, config-metrics-tile]
    - get: om-cli
      globs: om-linux
      passed: [config-elastic-runtime-tile, config-metrics-tile]

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

- name: disable-ert-errands
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [product-apply-changes]

  - task: apply-changes
    file: concourse-vsphere/tasks/disable-ert-errands/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

- name: post-ert-deploy-apply-changes
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [disable-ert-errands]
    - get: om-cli
      globs: om-linux
      passed: [product-apply-changes]

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

- name: upload-metrics-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [opsman-apply-changes]
    - get: pivnet-metrics-product
      params:
        globs:
        - "*.pivotal"
    - get: om-cli
      globs: om-linux
      passed: [opsman-apply-changes]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-metrics-tile
    file: concourse-vsphere/tasks/upload-metrics-tile/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      PIVNET_API_TOKEN: {{pivnet_token}}

- name: config-metrics-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      trigger: true
      passed: [upload-metrics-tile]
    - get: om-cli
      globs: om-linux
      passed: [upload-metrics-tile]

  - task: config-metrics-tile
    file: concourse-vsphere/tasks/config-ops-metrics/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      AZ_1: {{az_1_name}}
      NETWORK_NAME: {{network_name}}
      JMX_ADMIN_USR: {{jmx_admin_usr}}
      JMX_ADMIN_PWD: {{jmx_admin_pwd}}
      JMX_SECURITY_LOGGING: {{jmx_security_logging}}
      JMX_USE_SSL: {{jmx_use_ssl}}
