# Token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
github_token: ((github_token)) # [R] Your github token
github_repo: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
github_branch: master
github_username: ((github_username)) # [R] Your github username

iaas_type: vsphere

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr)) # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd)) # [R] Ops Manager admin password

debug: true
product_name: p-new-relic
product_identifier: newrelic-broker
product_version: ^1\.12\..*$

singleton_jobs_az: # [R] Place singleton jobs in an AZ
other_azs:         # [R] Balance other jobs in AZ's (comma-separated)
network_name:      # [R] Tile network name

allow_paid_service_plans: false
app_name: "NewRelicServiceBroker"
app_uri: "newrelic-broker"
app_version: "v1.12.9"
apply_open_security_group: false
newrelic_broker_enable_global_access_to_plans: true
nrplans: '{\"planName\":\"dev\",\"planDescription\":\"dev plan\",\"licenseKey\":\"SOMELICENSEKEY\"}'
org: "NewRelicServiceBroker-service-org"
space: "NewRelicServiceBroker-service-space"

errands_to_disable:

concourse_url:
concourse_user:
concourse_pwd:

pipeline-name:
team-name:
upgrade-pipeline-name:
