---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  SINGLETON_JOB_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  SERVICES_NETWORK:
  METRICS_POLLING_INTERVAL:
  RMQ_SERVER_INSTANCES:
  RMQ_HAPROXY_INSTANCES:
  RMQ_BROKER_INSTANCES:
  RMQ_ONDEMAND_INSTANCES:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  DISK_ALARM_THRESHOLD:
  RMQ_PLUGINS:
  RMQ_SSL_CERT:
  RMQ_PRIVATE_CERT:
  RMQ_CA_CERT:
  SSL_VERIFY:
  SSL_VERIFICATION_DEPTH:
  SSL_FAIL_IF_NO_PEER_CERT:
  ERLANG_COOKIE_NAME:
  RMQ_SERVER_CONFIG:
  RMQ_SERCURITY_OPTION:
  RMQ_NW_PARTITION_HANDLING:
  RMQ_SERVER_PORTS:
  RMQ_SERVER_STATIC_IPS:
  RMQ_ADMIN_USERNAME:
  RMQ_ADMIN_PASSWORD:
  RMQ_LOADBALANCER_DNS:
  IS_RMQ_POLICY_ENABLED:
  RMQ_POLICY_DEFINITION:
  ENABLE_SINGLE_NODE_PLAN:
  PLAN_NAME:
  PLAN_DESCRIPTION:
  PCF_MARKETPLACE_PRODUCT_IDENTIFIER:
  SERVICE_INSTANCE_COUNT:
  GLOBAL_SERVICE_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_AZS:
  ON_DEMAND_BROKER_VM_TYPE:
  VM_EXTENSIONS:
  RMQ_SERVER_NODE_PERSISTENT_DISK_SIZE:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-rabbitmq/task.sh
