---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_NAME:
  ON_DEMAND-BROKER_GLOBAL_SERVICE_INSTANCE_QUOTA:
  DISK_ALARM_THRESHOLD:
  METRICS_POLLING_INTERVAL:
  ON_DEMAND_BROKER_PLAN_1_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_1_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_1_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_1_FEATURES:
  ON_DEMAND_BROKER_PLAN_1_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_1_NAME:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_FEATURES:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_NAME:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_ENABLED_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_FEATURES:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_NAME:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_ENABLED_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_FEATURES:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_NAME:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_ENABLED_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_FEATURES:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_NAME:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_ENABLED_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_VM_EXTENSIONS:
  SYSLOG_SELECTOR:
  SYSLOG_SELECTOR_ENABLED_ADDRESS:
  SYSLOG_SELECTOR_ENABLED_PORT:
  SYSLOG_SELECTOR_ENABLED_SYSLOG_CA_CERT:
  SYSLOG_SELECTOR_ENABLED_SYSLOG_FORMAT:
  SYSLOG_SELECTOR_ENABLED_SYSLOG_PERMITTED_PEER:
  SYSLOG_SELECTOR_ENABLED_SYSLOG_TLS:
  SYSLOG_SELECTOR_ENABLED_SYSLOG_TRANSPORT:
  RABBITMQ_BROKER_DNS_HOST:
  RABBITMQ_BROKER_OPERATOR_SET_POLICY_ENABLED:
  RABBITMQ_BROKER_POLICY_DEFINITION:
  RABBITMQ_HAPROXY_STATIC_IPS:
  RABBITMQ_SERVER_CLUSTER_PARTITION_HANDLING:
  RABBITMQ_SERVER_CONFIG:
  RABBITMQ_SERVER_COOKIE:
  RABBITMQ_SERVER_PLUGINS:
  RABBITMQ_SERVER_PORTS:
  RABBITMQ_SERVER_RSA_CERTIFICATE:
  RABBITMQ_SERVER_SERVER_ADMIN_CREDENTIALS:
  RABBITMQ_SERVER_SSL_CACERT:
  RABBITMQ_SERVER_SSL_FAIL_IF_NO_PEER_CERT:
  RABBITMQ_SERVER_SSL_VERIFICATION_DEPTH:
  RABBITMQ_SERVER_SSL_VERIFY:
  RABBITMQ_SERVER_SSL_VERSIONS:
  RABBITMQ_SERVER_STATIC_IPS:
  RABBITMQ_SERVER_INSTANCES:
  RABBITMQ_SERVER_INSTANCE_TYPE:
  RABBITMQ_SERVER_PERSISTENT_DISK_MB:
  RABBITMQ_HAPROXY_INSTANCES:
  RABBITMQ_HAPROXY_INSTANCE_TYPE:
  RABBITMQ_BROKER_INSTANCES:
  RABBITMQ_BROKER_INSTANCE_TYPE:
  BROKER_REGISTRAR_INSTANCES:
  BROKER_REGISTRAR_INSTANCE_TYPE:
  DEREGISTER_AND_PURGE_INSTANCES_INSTANCES:
  DEREGISTER_AND_PURGE_INSTANCES_INSTANCE_TYPE:
  MULTITENANT_SMOKE_TESTS_INSTANCES:
  MULTITENANT_SMOKE_TESTS_INSTANCE_TYPE:
  ON_DEMAND_BROKER_SMOKE_TESTS_INSTANCES:
  ON_DEMAND_BROKER_SMOKE_TESTS_INSTANCE_TYPE:
  ON_DEMAND_BROKER_INSTANCES:
  ON_DEMAND_BROKER_INSTANCE_TYPE:
  ON_DEMAND_BROKER_PERSISTENT_DISK_MB:
  REGISTER_ON_DEMAND_SERVICE_BROKER_INSTANCES:
  REGISTER_ON_DEMAND_SERVICE_BROKER_INSTANCE_TYPE:
  DEREGISTER_ON_DEMAND_SERVICE_BROKER_INSTANCES:
  DEREGISTER_ON_DEMAND_SERVICE_BROKER_INSTANCE_TYPE:
  DELETE_ALL_SERVICE_INSTANCES_INSTANCES:
  DELETE_ALL_SERVICE_INSTANCES_INSTANCE_TYPE:
  UPGRADE_ALL_SERVICE_INSTANCES_INSTANCES:
  UPGRADE_ALL_SERVICE_INSTANCES_INSTANCE_TYPE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-p-rabbitmq/task.sh
