resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pipelines-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))
    username: ((github_username))
    password: ((github_token))

- name: pivnet-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((product_name))
    product_version: ((product_version))

jobs:

- name: upload-product
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      NO_PROXY: ((company_proxy_domain))
      OM_IP: ((om_ip))
      IAAS_TYPE: ((iaas_type))

- name: stage-product
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-product]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))
      PRODUCT_IDENTIFIER: ((product_identifier))

- name: config-product
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
      passed: [stage-product]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [stage-product]

  - task: config-tile
    file: pipelines-repo/tasks/config-jmx-bridge/task.yml
    params:
      PRODUCT_IDENTIFIER: ((product_identifier))
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))
      OPS_MGR_GENERATE_SSL_ENDPOINT: ((om_generate_ssl_endpoint))
      SINGLETON_AZ: ((singleton_az))
      OTHER_AZS: ((other_azs))
      NETWORK_NAME: ((network_name))
      JMX_ADMIN_USR: ((jmx_admin_usr))
      JMX_ADMIN_PWD: ((jmx_admin_pwd))
      NAT_ENABLED: ((nat_enabled))
      NAT_JMX_BRIDGE_IP: ((nat_jmx_bridge_ip))
      SECURITY_LOGGING_ENABLED: ((jmx_security_logging_enabled))
      JMX_USE_SSL: ((jmx_use_ssl))
      SSL_CERT: ((ssl_cert))
      SSL_PRIVATE_KEY: ((ssl_private_key))
      JMX_DOMAIN: ((jmx_domain))
      USE_METRIC_PREFIX: ((use_metric_prefix))
      MAXIMUS_INSTANCE_TYPE: ((maximus_instance_type))
      MAXIMUS_INSTANCES: ((maximus_instances))
      MAXIMUS_PERSISTENT_DISK_SIZE_MB: ((maximus_persistent_disk_size_mb))
      JMX_FIREHOSE_NOZZLE_INSTANCE_TYPE: ((jmx_firehose_nozzle_instance_type))
      JMX_FIREHOSE_NOZZLE_INSTANCES: ((jmx_firehose_nozzle_instances))
      JMX_FIREHOSE_NOZZLE_PERSISTENT_DISK_SIZE_MB: ((jmx_firehose_nozzle_persistent_disk_size_mb))
      INTEGRATION_TESTS_INSTANCE_TYPE: ((integration_tests_instance_type))
      INTEGRATION_TESTS_INSTANCES: ((integration_tests_instances))

- name: apply-changes
  plan:
  - aggregate:
    - get: pipelines-repo
      trigger: true
      passed: [config-product]
    - get: pivnet-product
      resource: pivnet-product
      params:
        globs:
        - "*.pivotal"
      passed: [config-product]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [config-product]

  - task: validate-apply-changes
    file: pipelines-repo/tasks/validate-apply-changes/task.yml
    params:
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))
      PRODUCT_IDENTIFIER: ((product_identifier))

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))

- name: update-metrics-ip-in-bosh
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [apply-changes]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [apply-changes]
      trigger: true

  - task: update-metrics-ip
    file: pipelines-repo/tasks/update-metrics-ip/task.yml
    params:
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))

- name: post-apply-changes
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [update-metrics-ip-in-bosh]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [update-metrics-ip-in-bosh]
      trigger: true

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: ((om_fqdn))
      OPS_MGR_USR: ((om_usr))
      OPS_MGR_PWD: ((om_pwd))

- name: set-upgrade-pipeline
  plan:
  - aggregate:
    - get: pipelines-repo
      trigger: true
      passed: [post-apply-changes]

  - task: set-upgrade-pipeline
    file: pipelines-repo/tasks/set-upgrade-pipeline/task.yml
    params:
      CONCOURSE_USERNAME: ((concourse_user))
      CONCOURSE_PASSWD: ((concourse_pwd))
      ATC_EXTERNAL_URL: ((concourse_url))
      BUILD_PIPELINE_NAME: ((pipeline-name))
      BUILD_TEAM_NAME: ((team-name))
      UPGRADE_PIPELINE_NAME: ((upgrade-pipeline-name))
