---


platform: linux


image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}


params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  CLOUD_CONTROLLER_ALLOW_APP_SSH_ACCESS:
  CLOUD_CONTROLLER_APPS_DOMAIN:
  CLOUD_CONTROLLER_DEFAULT_APP_MEMORY:
  CLOUD_CONTROLLER_DEFAULT_APP_SSH_ACCESS:
  CLOUD_CONTROLLER_DEFAULT_DISK_QUOTA_APP:
  CLOUD_CONTROLLER_DEFAULT_QUOTA_MAX_NUMBER_SERVICES:
  CLOUD_CONTROLLER_DEFAULT_QUOTA_MEMORY_LIMIT_MB:
  CLOUD_CONTROLLER_ENABLE_CUSTOM_BUILDPACKS:
  CLOUD_CONTROLLER_ENCRYPT_KEY:
  CLOUD_CONTROLLER_MAX_DISK_QUOTA_APP:
  CLOUD_CONTROLLER_MAX_FILE_SIZE:
  CLOUD_CONTROLLER_SECURITY_EVENT_LOGGING_ENABLED:
  CLOUD_CONTROLLER_STAGING_TIMEOUT_IN_SECONDS:
  CLOUD_CONTROLLER_SYSTEM_DOMAIN:
  DIEGO_BRAIN_STARTING_CONTAINER_COUNT_MAXIMUM:
  DIEGO_BRAIN_STATIC_IPS:
  DIEGO_CELL_EXECUTOR_DISK_CAPACITY:
  DIEGO_CELL_EXECUTOR_MEMORY_CAPACITY:
  DIEGO_CELL_INSECURE_DOCKER_REGISTRY_LIST:
  DOPPLER_MESSAGE_DRAIN_BUFFER_SIZE:
  HA_PROXY_INTERNAL_ONLY_DOMAINS:
  HA_PROXY_SKIP_CERT_VERIFY:
  HA_PROXY_STATIC_IPS:
  HA_PROXY_TRUSTED_DOMAIN_CIDRS:
  MYSQL_CLI_HISTORY:
  MYSQL_CLUSTER_PROBE_TIMEOUT:
  MYSQL_PREVENT_NODE_AUTO_REJOIN:
  MYSQL_REMOTE_ADMIN_ACCESS:
  MYSQL_MONITOR_POLL_FREQUENCY:
  MYSQL_MONITOR_RECIPIENT_EMAIL:
  MYSQL_MONITOR_WRITE_READ_DELAY:
  MYSQL_PROXY_SERVICE_HOSTNAME:
  MYSQL_PROXY_SHUTDOWN_DELAY:
  MYSQL_PROXY_STARTUP_DELAY:
  MYSQL_PROXY_STATIC_IPS:
  NFS_SERVER_BLOBSTORE_INTERNAL_ACCESS_RULES:
  AUTOSCALE_API_INSTANCE_COUNT:
  AUTOSCALE_INSTANCE_COUNT:
  AUTOSCALE_METRIC_BUCKET_COUNT:
  AUTOSCALE_SCALING_INTERVAL_IN_SECONDS:
  CC_API_RATE_LIMIT:
  CC_API_RATE_LIMIT_ENABLE_GENERAL_LIMIT:
  CC_API_RATE_LIMIT_ENABLE_UNAUTHENTICATED_LIMIT:
  CF_DIAL_TIMEOUT_IN_SECONDS:
  CF_NETWORKING_ENABLE_SPACE_DEVELOPER_SELF_SERVICE:
  CONTAINER_NETWORKING:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN_SILK_DNS_SERVERS:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN_SILK_ENABLE_LOG_TRAFFIC:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN_SILK_IPTABLES_ACCEPTED_UDP_LOGS_PER_SEC:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN_SILK_IPTABLES_DENIED_LOGS_PER_SEC:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN_SILK_NETWORK_CIDR:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN_SILK_NETWORK_MTU:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN_SILK_VTEP_PORT:
  CREDHUB_DATABASE:
  CREDHUB_DATABASE_EXTERNAL_HOST:
  CREDHUB_DATABASE_EXTERNAL_PASSWORD:
  CREDHUB_DATABASE_EXTERNAL_PORT:
  CREDHUB_DATABASE_EXTERNAL_TLS_CA:
  CREDHUB_DATABASE_EXTERNAL_USERNAME:
  CREDHUB_HSM_PROVIDER_CLIENT_CERTIFICATE:
  CREDHUB_HSM_PROVIDER_CLIENT_PRIVATE_KEY:
  CREDHUB_HSM_PROVIDER_PARTITION:
  CREDHUB_HSM_PROVIDER_PARTITION_PASSWORD:
  CREDHUB_HSM_PROVIDER_SERVERS:
  CREDHUB_KEY_ENCRYPTION_NAME:
  CREDHUB_KEY_ENCRYPTION_SECRET:
  CREDHUB_KEY_ENCRYPTION_IS_PRIMARY:
  ENABLE_GROOTFS:
  ENABLE_SERVICE_DISCOVERY_FOR_APPS:
  GARDEN_DISK_CLEANUP:
  GOROUTER_SSL_CIPHERS:
  HAPROXY_FORWARD_TLS:
  HAPROXY_FORWARD_TLS_ENABLE_BACKEND_CA:
  HAPROXY_HSTS_SUPPORT:
  HAPROXY_HSTS_SUPPORT_ENABLE_ENABLE_PRELOAD:
  HAPROXY_HSTS_SUPPORT_ENABLE_INCLUDE_SUBDOMAINS:
  HAPROXY_HSTS_SUPPORT_ENABLE_MAX_AGE:
  HAPROXY_MAX_BUFFER_SIZE:
  HAPROXY_SSL_CIPHERS:
  LOGGER_ENDPOINT_PORT:
  MYSQL_ACTIVITY_LOGGING:
  MYSQL_ACTIVITY_LOGGING_ENABLE_AUDIT_LOGGING_EVENTS:
  NETWORKING_POE_SSL_NAME:
  NETWORKING_POE_SSL_CERT_PEM:
  NETWORKING_POE_SSL_CERT_PRIVATE_KEY_PEM:
  NFS_VOLUME_DRIVER:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVER_HOST:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVER_PORT:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVICE_ACCOUNT_PASSWORD:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVICE_ACCOUNT_USER:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_USER_FQDN:
  PUSH_APPS_MANAGER_ACCENT_COLOR:
  PUSH_APPS_MANAGER_COMPANY_NAME:
  PUSH_APPS_MANAGER_CURRENCY_LOOKUP:
  PUSH_APPS_MANAGER_DISPLAY_PLAN_PRICES:
  PUSH_APPS_MANAGER_ENABLE_INVITATIONS:
  PUSH_APPS_MANAGER_FAVICON:
  PUSH_APPS_MANAGER_FOOTER_LINKS:
  PUSH_APPS_MANAGER_FOOTER_TEXT:
  PUSH_APPS_MANAGER_GLOBAL_WRAPPER_BG_COLOR:
  PUSH_APPS_MANAGER_GLOBAL_WRAPPER_FOOTER_CONTENT:
  PUSH_APPS_MANAGER_GLOBAL_WRAPPER_HEADER_CONTENT:
  PUSH_APPS_MANAGER_GLOBAL_WRAPPER_TEXT_COLOR:
  PUSH_APPS_MANAGER_LOGO:
  PUSH_APPS_MANAGER_MARKETPLACE_NAME:
  PUSH_APPS_MANAGER_NAV_LINKS:
  PUSH_APPS_MANAGER_PRODUCT_NAME:
  PUSH_APPS_MANAGER_SQUARE_LOGO:
  REP_PROXY_ENABLED:
  ROUTE_SERVICES:
  ROUTE_SERVICES_ENABLE_IGNORE_SSL_CERT_VERIFICATION:
  ROUTER_BACKEND_MAX_CONN:
  ROUTER_CLIENT_CERT_VALIDATION:
  ROUTER_ENABLE_PROXY:
  ROUTER_KEEPALIVE_CONNECTIONS:
  ROUTING_CUSTOM_CA_CERTIFICATES:
  ROUTING_DISABLE_HTTP:
  ROUTING_MINIMUM_TLS_VERSION:
  ROUTING_TLS_TERMINATION:
  SAML_ENTITY_ID_OVERRIDE:
  SAML_SIGNATURE_ALGORITHM:
  SECURE_SERVICE_INSTANCE_CREDENTIALS:
  SECURITY_ACKNOWLEDGEMENT:
  SMOKE_TESTS:
  SMOKE_TESTS_SPECIFIED_APPS_DOMAIN:
  SMOKE_TESTS_SPECIFIED_ORG_NAME:
  SMOKE_TESTS_SPECIFIED_SPACE_NAME:
  SMTP_ADDRESS:
  SMTP_AUTH_MECHANISM:
  SMTP_CRAMMD5_SECRET:
  SMTP_USER:
  SMTP_PASSWORD:
  SMTP_ENABLE_STARTTLS_AUTO:
  SMTP_FROM:
  SMTP_PORT:
  SYSLOG_HOST:
  SYSLOG_METRICS_TO_SYSLOG_ENABLED:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  SYSLOG_RULE:
  SYSLOG_TLS:
  SYSLOG_TLS_ENABLED_TLS_CA_CERT:
  SYSLOG_TLS_ENABLED_TLS_PERMITTED_PEER:
  SYSLOG_USE_TCP_FOR_FILE_FORWARDING_LOCAL_TRANSPORT:
  SYSTEM_BLOBSTORE:
  SYSTEM_BLOBSTORE_EXTERNAL_ACCESS_KEY:
  SYSTEM_BLOBSTORE_EXTERNAL_BUILDPACKS_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_DROPLETS_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_ENCRYPTION:
  SYSTEM_BLOBSTORE_EXTERNAL_ENCRYPTION_KMS_KEY_ID:
  SYSTEM_BLOBSTORE_EXTERNAL_ENDPOINT:
  SYSTEM_BLOBSTORE_EXTERNAL_PACKAGES_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_REGION:
  SYSTEM_BLOBSTORE_EXTERNAL_RESOURCES_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_SECRET_KEY:
  SYSTEM_BLOBSTORE_EXTERNAL_SIGNATURE_VERSION:
  SYSTEM_BLOBSTORE_EXTERNAL_VERSIONING:
  SYSTEM_BLOBSTORE_EXTERNAL_AZURE_ACCESS_KEY:
  SYSTEM_BLOBSTORE_EXTERNAL_AZURE_ACCOUNT_NAME:
  SYSTEM_BLOBSTORE_EXTERNAL_AZURE_BUILDPACKS_CONTAINER:
  SYSTEM_BLOBSTORE_EXTERNAL_AZURE_DROPLETS_CONTAINER:
  SYSTEM_BLOBSTORE_EXTERNAL_AZURE_ENVIRONMENT:
  SYSTEM_BLOBSTORE_EXTERNAL_AZURE_PACKAGES_CONTAINER:
  SYSTEM_BLOBSTORE_EXTERNAL_AZURE_RESOURCES_CONTAINER:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_ACCESS_KEY:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_BUILDPACKS_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_DROPLETS_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_PACKAGES_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_RESOURCES_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SECRET_KEY:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SERVICE_ACCOUNT_BUILDPACKS_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SERVICE_ACCOUNT_DROPLETS_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SERVICE_ACCOUNT_PACKAGES_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SERVICE_ACCOUNT_PROJECT_ID:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SERVICE_ACCOUNT_RESOURCES_BUCKET:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SERVICE_ACCOUNT_SERVICE_ACCOUNT_EMAIL:
  SYSTEM_BLOBSTORE_EXTERNAL_GCS_SERVICE_ACCOUNT_SERVICE_ACCOUNT_JSON_KEY:
  SYSTEM_DATABASE:
  SYSTEM_DATABASE_EXTERNAL_ACCOUNT_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_ACCOUNT_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_APP_USAGE_SERVICE_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_APP_USAGE_SERVICE_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_AUTOSCALE_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_AUTOSCALE_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_CCDB_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_CCDB_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_DIEGO_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_DIEGO_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_HOST:
  SYSTEM_DATABASE_EXTERNAL_LOCKET_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_LOCKET_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_NETWORKPOLICYSERVER_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_NETWORKPOLICYSERVER_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_NFSVOLUME_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_NFSVOLUME_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_NOTIFICATIONS_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_NOTIFICATIONS_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_PORT:
  SYSTEM_DATABASE_EXTERNAL_ROUTING_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_ROUTING_USERNAME:
  SYSTEM_DATABASE_EXTERNAL_SILK_PASSWORD:
  SYSTEM_DATABASE_EXTERNAL_SILK_USERNAME:
  TCP_ROUTING:
  TCP_ROUTING_ENABLE_RESERVABLE_PORTS:
  UAA:
  UAA_INTERNAL_PASSWORD_EXPIRES_AFTER_MONTHS:
  UAA_INTERNAL_PASSWORD_MAX_RETRY:
  UAA_INTERNAL_PASSWORD_MIN_LENGTH:
  UAA_INTERNAL_PASSWORD_MIN_LOWERCASE:
  UAA_INTERNAL_PASSWORD_MIN_NUMERIC:
  UAA_INTERNAL_PASSWORD_MIN_SPECIAL:
  UAA_INTERNAL_PASSWORD_MIN_UPPERCASE:
  UAA_LDAP_IDENTITY:
  UAA_LDAP_PASSWORD:
  UAA_LDAP_EMAIL_DOMAINS:
  UAA_LDAP_FIRST_NAME_ATTRIBUTE:
  UAA_LDAP_GROUP_SEARCH_BASE:
  UAA_LDAP_GROUP_SEARCH_FILTER:
  UAA_LDAP_LAST_NAME_ATTRIBUTE:
  UAA_LDAP_LDAP_REFERRALS:
  UAA_LDAP_MAIL_ATTRIBUTE_NAME:
  UAA_LDAP_SEARCH_BASE:
  UAA_LDAP_SEARCH_FILTER:
  UAA_LDAP_SERVER_SSL_CERT:
  UAA_LDAP_SERVER_SSL_CERT_ALIAS:
  UAA_LDAP_URL:
  UAA_SAML_DISPLAY_NAME:
  UAA_SAML_EMAIL_ATTRIBUTE:
  UAA_SAML_EMAIL_DOMAINS:
  UAA_SAML_ENTITY_ID_OVERRIDE:
  UAA_SAML_EXTERNAL_GROUPS_ATTRIBUTE:
  UAA_SAML_FIRST_NAME_ATTRIBUTE:
  UAA_SAML_LAST_NAME_ATTRIBUTE:
  UAA_SAML_NAME_ID_FORMAT:
  UAA_SAML_REQUIRE_SIGNED_ASSERTIONS:
  UAA_SAML_SIGN_AUTH_REQUESTS:
  UAA_SAML_SSO_NAME:
  UAA_SAML_SSO_URL:
  UAA_SAML_SSO_XML:
  UAA_DATABASE:
  UAA_DATABASE_EXTERNAL_HOST:
  UAA_DATABASE_EXTERNAL_PORT:
  UAA_DATABASE_EXTERNAL_UAA_PASSWORD:
  UAA_DATABASE_EXTERNAL_UAA_USERNAME:
  UAA_SESSION_COOKIE_MAX_AGE:
  UAA_SESSION_IDLE_TIMEOUT:
  ROUTER_DISABLE_INSECURE_COOKIES:
  ROUTER_DRAIN_WAIT:
  ROUTER_ENABLE_ISOLATED_ROUTING:
  ROUTER_ENABLE_WRITE_ACCESS_LOGS:
  ROUTER_ENABLE_ZIPKIN:
  ROUTER_EXTRA_HEADERS_TO_LOG:
  ROUTER_FRONTEND_IDLE_TIMEOUT:
  ROUTER_LB_HEALTHY_THRESHOLD:
  ROUTER_REQUEST_TIMEOUT_IN_SECONDS:
  ROUTER_STATIC_IPS:
  TCP_ROUTER_STATIC_IPS:
  UAA_APPS_MANAGER_ACCESS_TOKEN_LIFETIME:
  UAA_APPS_MANAGER_REFRESH_TOKEN_LIFETIME:
  UAA_CF_CLI_ACCESS_TOKEN_LIFETIME:
  UAA_CF_CLI_REFRESH_TOKEN_LIFETIME:
  UAA_CUSTOMIZE_PASSWORD_LABEL:
  UAA_CUSTOMIZE_USERNAME_LABEL:
  UAA_ISSUER_URI:
  UAA_PROXY_IPS_REGEX:
  UAA_PRIVATE_KEY_PEM:
  UAA_CERT_PEM:
  UAA_SERVICE_PROVIDER_KEY_PASSWORD:
  CONSUL_SERVER_INSTANCE_TYPE:
  CONSUL_SERVER_INSTANCES:
  CONSUL_SERVER_PERSISTENT_DISK_SIZE_MB:
  NATS_INSTANCE_TYPE:
  NATS_INSTANCES:
  NFS_SERVER_INSTANCE_TYPE:
  NFS_SERVER_INSTANCES:
  NFS_SERVER_PERSISTENT_DISK_SIZE_MB:
  MYSQL_PROXY_INSTANCE_TYPE:
  MYSQL_PROXY_INSTANCES:
  MYSQL_INSTANCE_TYPE:
  MYSQL_INSTANCES:
  MYSQL_INSTANCE_PERSISTENT_DISK_SIZE_MB:
  BACKUP_PREPARE_INSTANCE_TYPE:
  BACKUP_PREPARE_INSTANCES:
  BACKUP_PREPARE_PERSISTENT_DISK_SIZE_MB:
  UAA_INSTANCE_TYPE:
  UAA_INSTANCES:
  CLOUD_CONTROLLER_INSTANCE_TYPE:
  CLOUD_CONTROLLER_INSTANCES:
  HA_PROXY_INSTANCE_TYPE:
  HA_PROXY_INSTANCES:
  ROUTER_INSTANCE_TYPE:
  ROUTER_INSTANCES:
  MYSQL_MONITOR_INSTANCE_TYPE:
  MYSQL_MONITOR_INSTANCES:
  CLOCK_GLOBAL_INSTANCE_TYPE:
  CLOCK_GLOBAL_INSTANCES:
  CLOUD_CONTROLLER_WORKER_INSTANCE_TYPE:
  CLOUD_CONTROLLER_WORKER_INSTANCES:
  DIEGO_DATABASE_INSTANCE_TYPE:
  DIEGO_DATABASE_INSTANCES:
  DIEGO_BRAIN_INSTANCE_TYPE:
  DIEGO_BRAIN_INSTANCES:
  DIEGO_BRAIN_PERSISTENT_DISK_SIZE_MB:
  DIEGO_CELL_INSTANCE_TYPE:
  DIEGO_CELL_INSTANCES:
  DOPPLER_INSTANCE_TYPE:
  DOPPLER_INSTANCES:
  LOGGREGATOR_TC_INSTANCE_TYPE:
  LOGGREGATOR_TC_INSTANCES:
  TCP_ROUTER_INSTANCE_TYPE:
  TCP_ROUTER_INSTANCES:
  TCP_ROUTER_PERSISTENT_DISK_SIZE_MB:
  SYSLOG_ADAPTER_INSTANCE_TYPE:
  SYSLOG_ADAPTER_INSTANCES:
  SYSLOG_SCHEDULER_INSTANCE_TYPE:
  SYSLOG_SCHEDULER_INSTANCES:
  CREDHUB_INSTANCE_TYPE:
  CREDHUB_INSTANCES:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-ert/task.sh
