---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  ERT_SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  NETWORK_NAME:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  CC_API_RATE_LIMIT:
  GENERAL_LIMIT:
  UNAUTHENTICATED_LIMIT:
  CREDHUB_KEY_ENCRYPTION_PASSWORD:
  SECURE_SERVICE_INSTANCE_CREDENTIALS:
  CREDHUB_DATABASE:
  CREDHUB_DATABASE_EXTERNAL_HOST:
  CREDHUB_DATABASE_EXTERNAL_PORT:
  CREDHUB_DATABASE_EXTERNAL_USERNAME:
  CREDHUB_DATABASE_EXTERNAL_PASSWORD:
  CREDHUB_DATABASE_EXTERNAL_TLS_CA:
  NFS_VOLUME_DRIVER:
  LDAP_SERVICE_ACCOUNT_USER:
  LDAP_SERVICE_ACCOUNT_PASSWORD:
  LDAP_SERVER_HOST:
  LDAP_SERVER_PORT:
  LDAP_USER_FQDN:
  GARDEN_DISK_CLEANUP:
  ENABLE_GROOTFS:
  LOGGER_ENDPOINT_PORT:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  SYSLOG_TLS:
  TLS_CA_CERT:
  TLS_PERMITTED_PEER:
  NETWORKING_POE_SSL_CERT_PEM:
  NETWORKING_POE_SSL_CERT_PRIVATE_KEY_PEM:
  ROUTING_CUSTOM_CA_CERTIFICATES:
  ROUTING_DISABLE_HTTP:
  ROUTING_MINIMUM_TLS_VERSION:
  ROUTING_TLS_TERMINATION:
  GOROUTER_SSL_CIPHERS:
  HAPROXY_SSL_CIPHERS:
  HAPROXY_MAX_BUFFER_SIZE:
  HAPROXY_FORWARD_TLS:
  HAPROXY_FORWARD_TLS_BACKEND_CA:
  TCP_ROUTING:
  TCP_RESERVABLE_PORTS:
  ROUTER_FORWARD_CLIENT_CERT:
  ROUTER_BACKEND_MAX_CONN:
  ROUTE_SERVICES:
  IGNORE_SSL_CERT_VERIFICATION:
  CONTAINER_NETWORKING_NETWORK_CIDR:
  CONTAINER_NETWORKING_VTEP_PORT:
  CONTAINER_NETWORKING_LOG_TRAFFIC:
  IPTABLES_DENIED_LOGS_PER_SEC:
  IPTABLES_ACCEPTED_UDP_LOGS_PER_SEC:
  NETWORKING_POINT_OF_ENTRY:
  CONTAINER_NETWORKING:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN:
  CF_NETWORKING_ENABLE_SPACE_DEVELOPER_SELF_SERVICE:
  SECURITY_ACKNOWLEDGEMENT:
  CF_DIAL_TIMEOUT_IN_SECONDS:
  SMOKE_TESTS:
  SMOKE_TESTS_ORG_NAME:
  SMOKE_TESTS_SPACE_NAME:
  SMOKE_TESTS_APPS_DOMAIN:
  SMTP_FROM:
  SMTP_ADDRESS:
  SMTP_PORT:
  SMTP_IDENTITY:
  SMTP_PASSWORD:
  SMTP_ENABLE_STARTTLS_AUTO:
  SMTP_AUTH_MECHANISM:
  SMTP_CRAMMD5_SECRET:
  SYSTEM_BLOBSTORE:
  S3_ENDPOINT:
  S3_BUILDPACKS_BUCKET:
  S3_DROPLETS_BUCKET:
  S3_PACKAGES_BUCKET:
  S3_RESOURCES_BUCKET:
  S3_ACCESS_KEY:
  S3_SECRET_KEY:
  S3_SIGNATURE_VERSION:
  S3_REGION:
  S3_ENCRYPTION:
  GCS_BUILDPACKS_BUCKET:
  GCS_BUILDPACKS_BUCKET:
  GCS_PACKAGES_BUCKET:
  GCS_RESOURCES_BUCKET:
  GCS_ACCESS_KEY:
  GCS_SECRET_KEY:
  AZURE_BUILDPACKS_CONTAINER:
  AZURE_DROPLETS_CONTAINER:
  AZURE_PACKAGES_CONTAINER:
  AZURE_RESOURCES_CONTAINER:
  AZURE_ACCOUNT_NAME:
  AZURE_ACCESS_KEY:
  SYSTEM_DATABASE:
  EXTERNAL_MYSQL_HOST:
  EXTERNAL_MYSQL_PORT:
  EXTERNAL_MYSQL_ACCOUNT_USERNAME:
  EXTERNAL_MYSQL_ACCOUNT_PASSWORD:
  EXTERNAL_MYSQL_APP_USAGE_SERVICE_USERNAME:
  EXTERNAL_MYSQL_APP_USAGE_SERVICE_PASSWORD:
  EXTERNAL_MYSQL_AUTOSCALE_USERNAME:
  EXTERNAL_MYSQL_AUTOSCALE_PASSWORD:
  EXTERNAL_MYSQL_CCDB_USERNAME:
  EXTERNAL_MYSQL_CCDB_PASSWORD:
  EXTERNAL_MYSQL_DIEGO_USERNAME:
  EXTERNAL_MYSQL_DIEGO_PASSWORD:
  EXTERNAL_MYSQL_LOCKET_USERNAME:
  EXTERNAL_MYSQL_LOCKET_PASSWORD:
  EXTERNAL_MYSQL_NETWORKPOLICYSERVER_USERNAME:
  EXTERNAL_MYSQL_NETWORKPOLICYSERVER_PASSWORD:
  EXTERNAL_MYSQL_NFSVOLUME_USERNAME:
  EXTERNAL_MYSQL_NFSVOLUME_PASSWORD:
  EXTERNAL_MYSQL_NOTIFICATIONS_USERNAME:
  EXTERNAL_MYSQL_NOTIFICATIONS_PASSWORD:
  EXTERNAL_MYSQL_ROUTING_USERNAME:
  EXTERNAL_MYSQL_ROUTING_PASSWORD:
  EXTERNAL_MYSQL_SILK_USERNAME:
  EXTERNAL_MYSQL_SILK_PASSWORD:
  MYSQL_BACKUPS:
  MYSQL_BACKUPS_S3_ENDPOINT_URL:
  MYSQL_BACKUPS_S3_BUCKET_NAME:
  MYSQL_BACKUPS_S3_BUCKET_PATH:
  MYSQL_BACKUPS_S3_ACCESS_KEY_ID:
  MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY:
  MYSQL_BACKUPS_S3_CRON_SCHEDULE:
  MYSQL_BACKUPS_S3_BACKUP_ALL_MASTERS:
  MYSQL_BACKUPS_S3_REGION:
  MYSQL_BACKUPS_GCS_SERVICE_ACCOUNT_JSON:
  MYSQL_BACKUPS_GCS_PROJECT_ID:
  MYSQL_BACKUPS_GCS_BUCKET_NAME:
  MYSQL_BACKUPS_GCS_CRON_SCHEDULE:
  MYSQL_BACKUPS_GCS_BACKUP_ALL_MASTERS:
  MYSQL_BACKUPS_AZURE_STORAGE_ACCOUNT:
  MYSQL_BACKUPS_AZURE_STORAGE_ACCESS_KEY:
  MYSQL_BACKUPS_AZURE_CONTAINER:
  MYSQL_BACKUPS_AZURE_PATH:
  MYSQL_BACKUPS_AZURE_CRON_SCHEDULE:
  MYSQL_BACKUPS_AZURE_BACKUP_ALL_MASTERS:
  MYSQL_BACKUPS_SCP_SERVER:
  MYSQL_BACKUPS_SCP_PORT:
  MYSQL_BACKUPS_SCP_USER:
  MYSQL_BACKUPS_SCP_KEY:
  MYSQL_BACKUPS_SCP_DESTINATION:
  MYSQL_BACKUPS_SCP_CRON_SCHEDULE:
  MYSQL_BACKUPS_SCP_BACKUP_ALL_MASTERS:
  MYSQL_ACTIVITY_LOGGING:
  MYSQL_ACTIVITY_LOGGING_AUDIT_LOGGING_EVENTS:
  UAA_AUTH:
  PASSWORD_MIN_LENGTH:
  PASSWORD_MIN_UPPERCASE:
  PASSWORD_MIN_LOWERCASE:
  PASSWORD_MIN_NUMERIC:
  PASSWORD_MIN_SPECIAL:
  PASSWORD_EXPIRES_AFTER_MONTHS:
  PASSWORD_MAX_RETRY:
  SAML_SSO_NAME:
  SAML_DISPLAY_NAME:
  SAML_SSO_URL:
  SAML_NAME_ID_FORMAT:
  SAML_SSO_XML:
  SAML_SIGN_AUTH_REQUESTS:
  SAML_REQUIRE_SIGNED_ASSERTIONS:
  SAML_EMAIL_DOMAINS:
  SAML_FIRST_NAME_ATTRIBUTE:
  SAML_LAST_NAME_ATTRIBUTE:
  SAML_EMAIL_ATTRIBUTE:
  SAML_EXTERNAL_GROUPS_ATTRIBUTE:
  SAML_SIGNATURE_ALGORITHM:
  LDAP_URL:
  LDAP_IDENTITY:
  LDAP_PASSWORD:
  LDAP_SEARCH_BASE:
  LDAP_SEARCH_FILTER:
  LDAP_GROUP_SEARCH_BASE:
  LDAP_GROUP_SEARCH_FILTER:
  LDAP_SERVER_SSL_CERT:
  LDAP_SERVER_SSL_CERT_ALIAS:
  LDAP_MAIL_ATTRIBUTE_NAME:
  LDAP_EMAIL_DOMAINS:
  LDAP_FIRST_NAME_ATTRIBUTE:
  LDAP_LAST_NAME_ATTRIBUTE:
  LDAP_LDAP_REFERRALS:
  UAA_DATABASE:
  UAA_DATABASE_HOST:
  UAA_DATABASE_PORT:
  UAA_DATABASE_USERNAME:
  UAA_DATABASE_PASSWORD:
  BLOBSTORE_INTERNAL_ACCESS_RULES:
  MYSQL_PROXY_STATIC_IPS:
  MYSQL_PROXY_SERVICE_HOSTNAME:
  MYSQL_PROXY_STARTUP_DELAY:
  MYSQL_PROXY_SHUTDOWN_DELAY:
  MYSQL_CLI_HISTORY:
  MYSQL_CLUSTER_PROBE_TIMEOUT:
  PREVENT_NODE_AUTO_REJOIN:
  REMOTE_ADMIN_ACCESS:
  UAA_PRIVATE_KEY_PEM:
  UAA_CERT_PEM:
  UAA_PRIVATE_KEY_PASSPHRASE:
  APPS_MANAGER_ACCESS_TOKEN_LIFETIME:
  APPS_MANAGER_REFRESH_TOKEN_LIFETIME:
  CF_CLI_ACCESS_TOKEN_LIFETIME:
  CF_CLI_REFRESH_TOKEN_LIFETIME:
  CUSTOMIZE_USERNAME_LABEL:
  CUSTOMIZE_PASSWORD_LABEL:
  PROXY_IPS_REGEX:
  ISSUER_URI:
  CLOUD_CONTROLLER_ENCRYPT_KEY:
  MAX_FILE_SIZE:
  DEFAULT_APP_MEMORY:
  MAX_DISK_QUOTA_APP:
  DEFAULT_DISK_QUOTA_APP:
  ENABLE_CUSTOM_BUILDPACKS:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
  DEFAULT_QUOTA_MEMORY_LIMIT_MB:
  DEFAULT_QUOTA_MAX_NUMBER_SERVICES:
  STAGING_TIMEOUT_IN_SECONDS:
  ALLOW_APP_SSH_ACCESS:
  DEFAULT_APP_SSH_ACCESS:
  SECURITY_EVENT_LOGGING_ENABLED:
  HA_PROXY_STATIC_IPS:
  SKIP_CERT_VERIFY:
  PROTECTED_DOMAINS:
  TRUSTED_DOMAIN_CIDRS:
  ROUTER_STATIC_IPS:
  DISABLE_INSECURE_COOKIES:
  REQUEST_TIMEOUT_IN_SECONDS:
  FRONTEND_IDLE_TIMEOUT:
  DRAIN_WAIT:
  LB_HEALTHY_THRESHOLD:
  ENABLE_ZIPKIN:
  MAX_IDLE_CONNECTIONS:
  EXTRA_HEADERS_TO_LOG:
  ENABLE_ISOLATED_ROUTING:
  MYSQL_MONITOR_POLL_FREQUENCY:
  MYSQL_MONITOR_WRITE_READ_DELAY:
  MYSQL_MONITOR_RECIPIENT_EMAIL:
  DIEGO_BRAIN_STATIC_IPS:
  STARTING_CONTAINER_COUNT_MAXIMUM:
  EXECUTOR_DISK_CAPACITY:
  EXECUTOR_MEMORY_CAPACITY:
  INSECURE_DOCKER_REGISTRY_LIST:
  GARDEN_NETWORK_MTU:
  MESSAGE_DRAIN_BUFFER_SIZE:
  TCP_ROUTER_STATIC_IPS:
  COMPANY_NAME:
  ACCENT_COLOR:
  GLOBAL_WRAPPER_BG_COLOR:
  GLOBAL_WRAPPER_TEXT_COLOR:
  GLOBAL_WRAPPER_HEADER_CONTENT:
  GLOBAL_WRAPPER_FOOTER_CONTENT:
  LOGO:
  SQUARE_LOGO:
  FOOTER_TEXT:
  FOOTER_LINKS:
  NAV_LINKS_NAME_1:
  NAV_LINKS_HREF_1:
  NAV_LINKS_NAME_2:
  NAV_LINKS_HREF_2:
  NAV_LINKS_NAME_3:
  NAV_LINKS_HREF_3:
  APPS_MANAGER_PRODUCT_NAME:
  MARKETPLACE_NAME:
  ENABLE_INVITATIONS:
  DISPLAY_PLAN_PRICES:
  CURRENCY_LOOKUP:
  CONSUL_SERVER_INSTANCE_TYPE:
  CONSUL_SERVER_INSTANCES:
  CONSUL_SERVER_PERSISTENT_DISK_SIZE_MB:
  NATS_INSTANCE_TYPE:
  NATS_INSTANCES:
  NFS_SERVER_INSTANCE_TYPE:
  NFS_SERVER_INSTANCES:
  NFS_SERVER_PERSISTENT_DISK_SIZE_MB:
  MYSQL_PROXY_INSTANCE_TYPE:
  MYSQL_PROXY_INSTANCES:
  MYSQL_INSTANCE_TYPE:
  MYSQL_INSTANCES:
  MYSQL_INSTANCE_PERSISTENT_DISK_SIZE_MB:
  BACKUP_PREPARE_INSTANCE_TYPE:
  BACKUP_PREPARE_INSTANCES:
  BACKUP_PREPARE_PERSISTENT_DISK_SIZE_MB:
  UAA_INSTANCE_TYPE:
  UAA_INSTANCES:
  CLOUD_CONTROLLER_INSTANCE_TYPE:
  CLOUD_CONTROLLER_INSTANCES:
  HA_PROXY_INSTANCE_TYPE:
  HA_PROXY_INSTANCES:
  ROUTER_INSTANCE_TYPE:
  ROUTER_INSTANCES:
  MYSQL_MONITOR_INSTANCE_TYPE:
  MYSQL_MONITOR_INSTANCES:
  CLOCK_GLOBAL_INSTANCE_TYPE:
  CLOCK_GLOBAL_INSTANCES:
  CLOUD_CONTROLLER_WORKER_INSTANCE_TYPE:
  CLOUD_CONTROLLER_WORKER_INSTANCES:
  DIEGO_DATABASE_INSTANCE_TYPE:
  DIEGO_DATABASE_INSTANCES:
  DIEGO_BRAIN_INSTANCE_TYPE:
  DIEGO_BRAIN_INSTANCES:
  DIEGO_BRAIN_PERSISTENT_DISK_SIZE_MB:
  DIEGO_CELL_INSTANCE_TYPE:
  DIEGO_CELL_INSTANCES:
  DOPPLER_INSTANCE_TYPE:
  DOPPLER_INSTANCES:
  LOGGREGATOR_TC_INSTANCE_TYPE:
  LOGGREGATOR_TC_INSTANCES:
  TCP_ROUTER_INSTANCE_TYPE:
  TCP_ROUTER_INSTANCES:
  TCP_ROUTER_PERSISTENT_DISK_SIZE_MB:
  SYSLOG_ADAPTER_INSTANCE_TYPE:
  SYSLOG_ADAPTER_INSTANCES:
  CREDHUB_INSTANCE_TYPE:
  CREDHUB_INSTANCES:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-ert/task.sh
