pivnet_token: # [R] PivNet Access Token
github_token: # [R] Your github token
github_repo: https://github.com/rahul-kj/concourse-vsphere # [R] Pipelines github repo
github_branch: master
github_username: # [R] Your github username

company_proxy_domain: # [O] proxy domain
iaas_type: vsphere

## Ops Manager installation meta data
ops_mgr_ip: # [O] Ops Manager IP if behind proxy
ops_mgr_host: # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: # [R] Ops Manager admin user
ops_mgr_pwd: # [R] Ops Manager admin password

product_name: apm
product_identifier: apm
product_version: ^1\.4\..*$

singleton_jobs_az: # [R] Place singleton jobs in an AZ
other_azs: # [R] Balance other jobs in AZ's
network_name: # [R] Tile network name

mysql_logqueue_instance_count: 1
elasticsearch_logqueue_instance_count: 1
ingestor_instance_count: 1
server_instance_count: 1
logs_retention_window: 14
metrics_retention_window: 14

elasticsearch_master_instance_type: large
elasticsearch_master_instances: 1
elasticsearch_master_persistent_disk_size: 10240
elasticsearch_data_instance_type: xlarge
elasticsearch_data_instances: 4
elasticsearch_data_persistent_disk_size: 102400
redis_instance_type: medium
redis_instances: 1
redis_disk_size: 102400
mysql_instance_type: xlarge
mysql_persistent_disk_size: 512000

errands_to_disable: "push-apps,migrate-data-to-1-4,smoke-tests,delete-metrics-1-3-space"

concourse_user:
concourse_pwd:
concourse_url:
pipeline-name:
team-name:
upgrade-pipeline-name:
