pivnet_token: # [R] PivNet Access Token
github_token: # [R] Your github token
github_repo: https://github.com/rahul-kj/concourse-vsphere # [R] Pipelines github repo
github_branch: master
github_username: # [R] Your github username

company_proxy_domain: # [O] proxy domain
iaas_type: vsphere

## Ops Manager installation meta data
ops_mgr_ip: # [O] Ops Manager IP if behind proxy
ops_mgr_host: # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: # [R] Ops Manager admin user
ops_mgr_pwd: # [R] Ops Manager admin password

product_name: apm
product_identifier: apm
product_version: ^1\.3\..*$

singleton_job_az:
other_azs:
network_name:
mysql_monitor_email:
errands_to_disable:
mysql_logqueue_instance_count: 2
elasticsearch_logqueue_instance_count: 4
ingestor_instance_count: 4
elasticsearch_master_instance_type: large
elasticsearch_master_instances: 1
elasticsearch_master_persistent_disk_size: 10240
elasticsearch_data_instance_type: xlarge
elasticsearch_data_instances: 4
elasticsearch_data_persistent_disk_size: 102400
mysql_server_instance_type: xlarge
mysql_server_instances: 3
mysql_server_persistent_disk_size: 102400
mysql_proxy_instance_type: medium.disk
mysql_proxy_instances: 2
