---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  BROKER_MAX_INSTANCES:
  BUILDPACK:
  DISABLE_CERT_CHECK:
  INSTANCES_APP_PUSH_TIMEOUT:
  PERSISTENCE_STORE_SERVICE:
  PERSISTENCE_STORE_SERVICE_PLAN:
  MESSAGE_BUS_SERVICE:
  MESSAGE_SERVICE_BUS_PLAN:
  ENABLE_GLOBAL_ACCESS:
  SECURE_CREDENTIALS:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-spring-cloud-services/task.sh
