---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:
  MYSQL_SKIP_NAME_RESOLVE:
  HEALTHWATCH_FOUNDATION_NAME:
  HEALTHWATCH_FORWARDER_INGESTOR_INSTANCES:
  HEALTHWATCH_FORWARDER_LOADER_INSTANCES:
  HEALTHWATCH_FORWARDER_CANARY_INSTANCES:
  HEALTHWATCH_FORWARDER_BOSH_HEALTH_INSTANCES:
  HEALTHWATCH_FORWARDER_BOSH_TASKS_INSTANCES:
  HEALTHWATCH_FORWARDER_CLI_INSTANCES:
  HEALTHWATCH_FORWARDER_OPSMAN_INSTANCES:
  HEALTHWATCH_FORWARDER_HEALTHCHECK_AZ:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-healthwatch/task.sh
