---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  RETENTION_PERIOD:
  PARSER_OUTPUTS:
  MAX_QUEUE_LENGTH:
  EVENT_TYPES:
  ELASTIC_SEARCH_INSTANCES:
  ELASTIC_SEARCH_INSTANCE_TYPE:
  ELASTICSEARCH_MASTER_PERSISTENT_DISK_MB:
  ELASTIC_DATA_INSTANCE_TYPE:
  ELASTIC_DATA_INSTANCES:
  ELASTICSEARCH_DATA_PERSISTENT_DISK_MB:
  PARSER_INSTANCE_TYPE:
  PARSER_INSTANCES:
  INGESTOR_INSTANCE_TYPE:
  INGESTOR_INSTANCES:
  KIBANA_INSTANCE_TYPE:
  KIBANA_INSTANCES:
  MONITOR_INSTANCE_TYPE:
  MONITOR_INSTANCES:
  MONITOR_PERSISTENT_DISK_MB:
  FIREHOSE_TO_SYSLOG_INSTANCE_TYPE:
  FIREHOSE_TO_SYSLOG_INSTANCES:

inputs:
  - name: pipelines-repo
  - name: om-cli

run:
  path: pipelines-repo/tasks/config-logsearch/task.sh
